version: "3.8"

services:
  studypal_db:
    image: postgres:latest
    container_name: studypal_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - studypal_db_data:/var/lib/postgresql/data

volumes:
  studypal_db_data:
